GET http://localhost:5000/


###

POST http://localhost:5000/add
Content-Type: application/json

{
    "title": "cvb",
    "author": "qqwerqwqerq",
    "genre": "qqweqrwqerq",
    "publication_date": "2002-03-1",
    "description": "weqrwe"
}

###

DELETE http://localhost:5000/delete/f2ff139c-0cc6-482b-88a0-36ba46057d12


###

PUT http://localhost:5000/edit/5dedbc72-3400-466c-938a-874ce4842710
Content-Type: application/json

{
    "title": "qqq",
    "author": "qqq",
    "genre": "qqq",
    "publication_date": "2002-03-1",
    "description": "qqq"
}